baseurl = "/"
languageCode = "eu"
title = "Juan Abasolo"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Niri buruz"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Telegram"
    url = "https://t.me/JuanAbasolo"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/JuanAbasolo"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/juanbasolo1"
    weight = 4

[params]
    description = "Juan Abasoloren webgune pertsonala"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.jpg"
    width = 50
    height = 50
    alt = ""


